# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Anomalia"),
                            ("trend", "Tendência"),
                            ("recommendation", "Recomendação"),
                            ("alert", "Alerta"),
                        ],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "ai_analysis",
                    models.TextField(blank=True, verbose_name="análise da IA"),
                ),
                (
                    "data_context",
                    models.JSONField(default=dict, verbose_name="contexto dos dados"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lido")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="importante"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="dashboards.dashboard",
                        verbose_name="dashboard",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="organizations.organization",
                        verbose_name="organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "insight",
                "verbose_name_plural": "insights",
                "ordering": ["-created_at"],
            },
        ),
    ]
