# Generated by Django 5.2.8 on 2025-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("sales", "Vendas"),
                            ("financial", "Financeiro"),
                            ("performance", "Performance"),
                            ("custom", "Personalizado"),
                        ],
                        default="custom",
                        max_length=50,
                        verbose_name="template",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="configuração")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="público"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "dashboard",
                "verbose_name_plural": "dashboards",
                "ordering": ["-created_at"],
            },
        ),
    ]
