# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("datasources", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="criado por",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="datasources",
            field=models.ManyToManyField(
                blank=True,
                related_name="dashboards",
                to="datasources.datasource",
                verbose_name="fontes de dados",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to="organizations.organization",
                verbose_name="organização",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="compartilhado com",
            ),
        ),
    ]
