# Generated by Django 5.2.8 on 2025-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="estado"),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "country",
                    models.CharField(default="BR", max_length=2, verbose_name="país"),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("accounting", "Contabilidade"),
                            ("logistics", "Logística e Transporte"),
                            ("marketing", "Marketing e Publicidade"),
                            ("retail", "Varejo"),
                            ("ecommerce", "E-commerce"),
                            ("services", "Serviços"),
                            ("manufacturing", "Indústria"),
                            ("technology", "Tecnologia"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="setor",
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 1-10, 11-50, 51-200, etc.",
                        max_length=50,
                        verbose_name="tamanho da empresa",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="plano",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="trial termina em"
                    ),
                ),
                (
                    "subscription_active",
                    models.BooleanField(default=True, verbose_name="assinatura ativa"),
                ),
                (
                    "max_users",
                    models.IntegerField(default=1, verbose_name="máximo de usuários"),
                ),
                (
                    "max_dashboards",
                    models.IntegerField(default=2, verbose_name="máximo de dashboards"),
                ),
                (
                    "max_datasources",
                    models.IntegerField(
                        default=3, verbose_name="máximo de fontes de dados"
                    ),
                ),
                (
                    "max_ai_queries",
                    models.IntegerField(
                        default=50, verbose_name="máximo de perguntas IA/mês"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configurações"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "organização",
                "verbose_name_plural": "organizações",
                "ordering": ["-created_at"],
            },
        ),
    ]
