# Generated by Django 5.2.8 on 2025-11-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="max_ai_queries",
        ),
        migrations.AddField(
            model_name="organization",
            name="ai_insights_used_this_month",
            field=models.IntegerField(
                default=0, verbose_name="insights IA usados este mês"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_auto_sync",
            field=models.BooleanField(
                default=False, verbose_name="pode sincronizar automaticamente"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_customize_dashboards",
            field=models.BooleanField(
                default=False, verbose_name="pode customizar dashboards"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_export_without_watermark",
            field=models.BooleanField(
                default=False, verbose_name="pode exportar sem marca d'água"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_share_dashboards",
            field=models.BooleanField(
                default=False, verbose_name="pode compartilhar dashboards"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_use_api",
            field=models.BooleanField(default=False, verbose_name="pode usar API"),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_use_predictive_analytics",
            field=models.BooleanField(
                default=False, verbose_name="pode usar análise preditiva"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="can_use_whatsapp",
            field=models.BooleanField(default=False, verbose_name="pode usar WhatsApp"),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_white_label",
            field=models.BooleanField(default=False, verbose_name="tem white label"),
        ),
        migrations.AddField(
            model_name="organization",
            name="last_ai_reset",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="último reset de IA"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_ai_insights_per_month",
            field=models.IntegerField(
                default=3, verbose_name="máximo de insights IA/mês"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_charts_per_dashboard",
            field=models.IntegerField(
                default=4, verbose_name="máximo de gráficos por dashboard"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_data_rows",
            field=models.IntegerField(
                default=5000, verbose_name="máximo de linhas de dados"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="max_scheduled_reports",
            field=models.IntegerField(
                default=0, verbose_name="máximo de relatórios agendados"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_dashboards",
            field=models.IntegerField(default=1, verbose_name="máximo de dashboards"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_datasources",
            field=models.IntegerField(
                default=1, verbose_name="máximo de fontes de dados"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
                verbose_name="plano",
            ),
        ),
    ]
