# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID externo"
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID do cliente"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("canceled", "Cancelado"),
                            ("past_due", "Vencido"),
                            ("trialing", "Trial"),
                        ],
                        default="trialing",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="início do período"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fim do período"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelado em"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                        verbose_name="organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "assinatura",
                "verbose_name_plural": "assinaturas",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID externo"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="BRL", max_length=3, verbose_name="moeda"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("open", "Aberto"),
                            ("paid", "Pago"),
                            ("void", "Cancelado"),
                            ("uncollectible", "Não cobrável"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("invoice_date", models.DateTimeField(verbose_name="data da fatura")),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de vencimento"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="pago em"),
                ),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF da fatura",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.subscription",
                        verbose_name="assinatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "fatura",
                "verbose_name_plural": "faturas",
                "ordering": ["-invoice_date"],
            },
        ),
    ]
