# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("google_sheets", "Google Sheets"),
                            ("excel_online", "Excel Online"),
                            ("csv_upload", "Upload CSV"),
                            ("xlsx_upload", "Upload Excel"),
                            ("database", "Banco de Dados"),
                            ("api", "API"),
                        ],
                        max_length=50,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "connection_config",
                    models.JSONField(
                        default=dict, verbose_name="configuração de conexão"
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True, verbose_name="sincronização automática"
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "A cada hora"),
                            ("6hours", "A cada 6 horas"),
                            ("daily", "Diariamente"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="frequência de sincronização",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última sincronização"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasources",
                        to="organizations.organization",
                        verbose_name="organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "fonte de dados",
                "verbose_name_plural": "fontes de dados",
                "ordering": ["-created_at"],
            },
        ),
    ]
