# Generated by Django 5.2.8 on 2025-11-09 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("custom", "Personalizado"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="frequência",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("both", "Ambos"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="método de entrega",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="destinatários"),
                ),
                (
                    "template_config",
                    models.JSONField(
                        default=dict, verbose_name="configuração do template"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último envio"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="dashboards.dashboard",
                        verbose_name="dashboard",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="organizations.organization",
                        verbose_name="organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "relatório",
                "verbose_name_plural": "relatórios",
                "ordering": ["-created_at"],
            },
        ),
    ]
